### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ghost** [ConcaveTrillion/pg-hilairebelloc-theservilestate#1]
Hello!

First of all, apologies if opening an issue here is not the best way of asking this, but I had no other way to get in contact.

I am also proofreading texts for submission to PG. I am aware that you need to submit a plaintext and an html file to have a work accepted. How did you generate the html file from the txt? I am not going through Distributed Proofreaders either so I would appreciate any other tips you could spare! :)

Thank you!

**Comment by ConcaveTrillion** [comment]
Hello,

No problem! Feel free to send me a email message to follow up - my username at gmail.

So, I created the HTML file first from the page scans/transcriptions, and proofread that.

I found it was easier to do all the proofreading using html (I could resize the text in the browser and put it side by side with a page scan).

*Then* I created the txt file by doing a bunch of find/replace regular expressions (I used the Visual Studio Code editor for this) on the HTML file:

- `</p>` with two carriage returns, `<p>` with nothing
- replace `<i></i>` or `<em></em>` italics with underscores (`_italictext_`)
- replace smallcaps (span class="smallcaps") with slashes (`/smallcaptext/`)
- `<hr/>` replaced by `\n* * * * *\n`
- `<h3>` with two carriage returns below, the `<div>` stuff for sectioning with two carriage returns above.
- The endnotes with simple brackets and numbers, with the list at the end.

In theory, you could sort of do the reverse of that - replacing the various marks in the ascii with html.

I then formatted the file to do the text wrap using a Visual Studio Code Extension called "Rewrap":
https://stkb.github.io/Rewrap/

I *think* I wrapped it at column 76. 

The member of the whitewasher team that I worked with was helpful. There were two tools they had me use as well - `gutspell` and `gutcheck` to check spelling and format of the HTML file. 

This is an old FAQ but I found it helpful (especially V52 about proofing)
https://web.archive.org/web/20191203121655/http://www.gutenberg.org/wiki/Gutenberg:Volunteers'_FAQ

CT
